import React,{useState,useEffect,useRef} from 'react';
import {Upload,Play,Download,ArrowUpRight,RefreshCw,CheckCircle2,AlertTriangle,FileText,ChevronLeft,ChevronRight} from 'lucide-react';
import {api,download} from './api';
const pct=v=>v==null?'—':`${(v*100).toFixed(2)}%`;
const human=s=>String(s??'').replaceAll('_',' ');
const active=s=>['queued','processing'].includes(s);
function Badge({value}){return <span className={`badge ${String(value).toLowerCase()}`}>{human(value)}</span>}
export default function CsvTesting({token,model,onOpen,onRefresh}){
 const [file,setFile]=useState(null),[sampleSize,setSampleSize]=useState('100'),[seed,setSeed]=useState('42'),[runs,setRuns]=useState([]),[run,setRun]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[offset,setOffset]=useState(0),[filter,setFilter]=useState('all');
 const selectedId=useRef(null),input=useRef(),requestId=useRef(0);
 async function refreshList(){try{const list=await api('/csv-runs',{token});setRuns(list)}catch(e){setError(e.message)}}
 async function select(id){selectedId.current=id;const revision=++requestId.current;setOffset(0);setFilter('all');setError('');try{const result=await api('/csv-runs/'+id,{token});if(revision===requestId.current)setRun(result)}catch(e){setError(e.message)}}
 useEffect(()=>{setRun(null);selectedId.current=null;refreshList();return()=>{requestId.current++}},[token]);
 useEffect(()=>{if(!run||!active(run.status))return;let stopped=false,timer;async function poll(){try{const result=await api('/csv-runs/'+run.id,{token});if(!stopped&&selectedId.current===run.id){setRun(result);if(!active(result.status)){refreshList();onRefresh()}}}catch(e){if(!stopped)setError(e.message)}if(!stopped)timer=setTimeout(poll,1500)}timer=setTimeout(poll,1200);return()=>{stopped=true;clearTimeout(timer)}},[run?.id,run?.status,token]);
 async function analyze(e){e.preventDefault();if(!file)return;setBusy(true);setError('');try{if(file.size>50*1024*1024)throw Error('Maximum CSV size is 50 MB.');const body=new FormData();body.append('file',file);body.append('sample_size',sampleSize);body.append('seed',seed);const result=await api('/csv-runs',{method:'POST',token,body,timeoutMs:120000});selectedId.current=result.id;setRun({...result,results:[]});setOffset(0);setFilter('all');await refreshList()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const metrics=run?.metrics||{},results=run?.results||[];
 const rows=results.filter(r=>filter==='all'||filter==='errors'&&r.error||filter==='incorrect'&&!r.error&&r.truth?.class!=null&&r.prediction!==r.truth.class||filter==='normal'&&r.detection==='Normal'||filter==='malicious'&&r.detection==='Malicious');
 const distribution=Object.entries(metrics.predicted_counts||{}).sort((a,b)=>b[1]-a[1]);
 return <div className="csv-page">
 <section className="csv-intro panel"><div className="panel-heading"><div><h2>Test your trained model</h2><p>Upload UNSW-NB15 test records to demonstrate all six expected outcomes.</p></div><Badge value={model?.ready?'model ready':'model unavailable'}/></div><div className="csv-intro-body"><p>{model?.ready?`${model.name} · ${model.classes.length} trained classes. CSV inference is ready; no EVE compatibility flag change is needed.`:model?.reason||'Checking model readiness…'}</p><div className="outcome-strip">{['Detect','Classify','Score','Explain','Recommend','Visualize'].map((name,i)=><span key={name}><b>{i+1}</b>{name}</span>)}</div><form className="csv-upload" onSubmit={analyze}><label className="csv-file-label">Testing CSV<input ref={input} aria-label="Testing CSV" type="file" accept=".csv,text/csv" required onChange={e=>setFile(e.target.files[0]||null)}/></label><label>Rows to analyze<select aria-label="Rows to analyze" value={sampleSize} onChange={e=>setSampleSize(e.target.value)}>{[10,100,250,1000].map(n=><option key={n} value={n}>{n} rows</option>)}</select></label><label>Sampling seed<input aria-label="Sampling seed" type="number" min="0" max="2147483647" required value={seed} onChange={e=>setSeed(e.target.value)}/></label><button className="button accent" disabled={busy||!file||!model?.ready}><Play size={15}/>{busy?'Uploading…':'Analyze CSV'}</button></form><p className="help">Up to 50 MB. Larger files are sampled uniformly using the seed. Ground-truth columns are used only for evaluation. This run does not train the model or automatically call Mistral.</p></div></section>
 {error&&<div className="error" role="alert">{error}</div>}
 <div className="csv-history"><label>Saved test runs<select aria-label="Saved test runs" value={run?.id||''} onChange={e=>e.target.value&&select(e.target.value)}><option value="">Choose a run</option>{runs.map(r=><option key={r.id} value={r.id}>{r.filename} · {r.sample_rows} rows · {human(r.status)} · {r.id.slice(0,6)}</option>)}</select></label><button className="button" onClick={refreshList}><RefreshCw size={14}/>Refresh runs</button>{run&&<button className="button" onClick={()=>download(`triage6-evaluation-${run.id}.json`,JSON.stringify(run,null,2),'application/json')}><Download size={14}/>Export evaluation</button>}</div>
 {run&&<><section className="run-status"><div><strong>{run.filename}</strong><Badge value={run.status}/></div><p>{run.processed} / {run.sample_rows} sampled rows processed · {run.total_rows.toLocaleString()} rows in uploaded file · {run.failures} failed</p><progress max={run.sample_rows} value={run.processed}/><small>{run.metadata?.sampling}. {run.sample_rows===run.total_rows?'All uploaded records are selected for this run.':'Metrics below cover this sample, not your full CSV.'}</small>{run.error&&<div className="error">{run.error}</div>}{run.metadata?.training_filename_match&&<div className="error"><AlertTriangle size={16}/>This filename matches the model’s training source. These results should not be presented as held-out test performance.</div>}</section>
 <section className="metrics csv-metrics">{[['Detection accuracy',metrics.binary_accuracy,`${metrics.binary_labelled_rows||0} rows with valid binary truth`],['Attack-class accuracy',metrics.class_accuracy,`${metrics.class_labelled_rows||0} rows with valid class truth`],['Attack precision',metrics.attack_precision,'Of predicted attacks, how many were correct'],['Attack recall',metrics.attack_recall,'Of actual attacks, how many were found'],['Attack F1',metrics.attack_f1,'Combined precision and recall'],['False-positive rate',metrics.false_positive_rate,'Normal rows incorrectly flagged']].map(([title,value,note])=><article className="metric" key={title}><div>{title}</div><strong>{pct(value)}</strong><small>{note}</small></article>)}</section>
 <div className="csv-coverage"><CheckCircle2 size={15}/><span>{metrics.scored_rows||0} scored · {metrics.shap_explained_rows||0} with SHAP · {metrics.unknown_protocol_rows||0} unseen-protocol rows · {metrics.missing_or_invalid_binary_labels||0} scored rows without usable binary labels</span></div><p className="help csv-caveat">Missing denominators display “—”. Failed rows are excluded from metrics and remain visible below. Predictions are estimates; accuracy depends on using a genuinely held-out file. Sampling results can differ from the full-file evaluation.</p>
 <div className="overview-grid"><section className="panel"><div className="panel-heading"><div><h2>Predicted attack patterns</h2><p>Counts from successfully scored sample records</p></div></div><div className="bars">{distribution.map(([name,count])=><div className="bar-row" key={name}><span className="class-name">{name}</span><div className="track"><div className={`bar ${name==='Normal'?'low':'critical'}`} style={{width:`${count/Math.max(1,metrics.scored_rows||0)*100}%`}}/></div><b>{count}</b></div>)}{!distribution.length&&<p className="help">Waiting for predictions.</p>}</div></section><section className="panel"><div className="panel-heading"><div><h2>Normal vs malicious</h2><p>Ground truth × model prediction</p></div></div><div className="binary-matrix"><div/><div>Predicted Normal</div><div>Predicted Malicious</div><div>Actual Normal</div><strong className="correct-cell">{metrics.binary_confusion?.tn??'—'}<small>True negative</small></strong><strong>{metrics.binary_confusion?.fp??'—'}<small>False positive</small></strong><div>Actual Malicious</div><strong>{metrics.binary_confusion?.fn??'—'}<small>False negative</small></strong><strong className="correct-cell">{metrics.binary_confusion?.tp??'—'}<small>True positive</small></strong></div><p className="help matrix-note">Detection follows the highest-probability class: Normal or an attack class. The aggregate malicious probability is a separate score.</p></section></div>
 <section className="panel"><div className="panel-heading"><div><h2>Record predictions</h2><p>Open a record for SHAP features, confidence and defensive guidance.</p></div><select aria-label="Filter CSV results" value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0)}}><option value="all">All sampled records</option><option value="normal">Predicted Normal</option><option value="malicious">Predicted Malicious</option><option value="incorrect">Incorrect attack class</option><option value="errors">Processing errors</option></select></div><div className="table-wrap"><table><thead><tr><th>CSV row</th><th>Detection</th><th>Attack class</th><th>Class confidence</th><th>Malicious probability</th><th>Severity</th><th>Ground truth</th><th/></tr></thead><tbody>{rows.slice(offset,offset+25).map(r=><tr key={r.row}><td>{r.event_id?<button className="text-button" onClick={()=>onOpen(r.event_id)}>Row {r.row}</button>:`Row ${r.row}`}</td>{r.error?<td colSpan="7" className="error-text">{r.error}</td>:<><td><Badge value={r.detection}/></td><td>{r.prediction}</td><td>{pct(r.class_confidence)}</td><td>{pct(r.model_probability)}</td><td><Badge value={r.severity}/></td><td>{r.truth?.class??(r.truth?.binary===0?'Normal':r.truth?.binary===1?'Malicious':'Unavailable')}<small>{r.truth?.note|| (r.truth?.class?(r.truth.class===r.prediction?'Correct class':'Incorrect class'):'Evaluation only')}</small></td><td><button className="icon-button" aria-label={`Explain CSV row ${r.row}`} onClick={()=>onOpen(r.event_id)}><ArrowUpRight size={16}/></button></td></>}</tr>)}</tbody></table></div>{!rows.length&&<div className="empty">{active(run.status)?'Processing sample records…':'No results match this filter.'}</div>}<div className="table-footer"><span>{rows.length?`${offset+1}–${Math.min(offset+25,rows.length)} of ${rows.length}`:'0 records'} · CSV row means data-record index, excluding header</span><div><button className="icon-button" aria-label="Previous CSV page" disabled={offset===0} onClick={()=>setOffset(offset-25)}><ChevronLeft size={16}/></button><button className="icon-button" aria-label="Next CSV page" disabled={offset+25>=rows.length} onClick={()=>setOffset(offset+25)}><ChevronRight size={16}/></button></div></div></section>
 <details className="class-matrix panel"><summary>Per-class scores and attack-class confusion matrix</summary><div className="table-wrap"><table><thead><tr><th>Class</th><th>True support</th><th>Precision</th><th>Recall</th><th>F1</th></tr></thead><tbody>{(metrics.per_class||[]).map(c=><tr key={c.class}><td>{c.class}</td><td>{c.support}</td><td>{pct(c.precision)}</td><td>{pct(c.recall)}</td><td>{pct(c.f1)}</td></tr>)}</tbody></table></div><p className="help matrix-note">Rows = true class; columns = predicted class. Zero-support classes have no measured recall.</p><div className="table-wrap"><table><thead><tr><th>True / predicted</th>{(metrics.classes||[]).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{(metrics.confusion_matrix||[]).map((row,i)=><tr key={i}><td>{metrics.classes[i]}</td>{row.map((n,j)=><td className={i===j?'correct-cell':''} key={j}>{n}</td>)}</tr>)}</tbody></table></div></details>
 </>}
 {!run&&<div className="empty"><FileText size={34}/><h3>Start with 100 test records</h3><p>Your trained model runs locally. Inspect predictions before using optional cloud explanations.</p></div>}
 </div>
}
